### ISSUE TITLE
Failed to load c++ bson extension

### ISSUE THREAD

**Issue by Digital-Thor** [vsivsi/meteor-file-collection#57] opened 2015-06-06 06:39 UTC
I'm getting the following error on 64bit Windows 7 version of Meteor:
```
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```
I see that [Issue 20](https://github.com/vsivsi/meteor-file-collection/issues/20) dealt with this in Linux, but it looks like it may still be lingering in Windows.

**Comment by vsivsi** [comment] 2015-06-06 07:15
Hi, since that old issue, Meteor has changed how packages are deployed. Packages with npm dependencies that include native components are now pre-built when the package is published/deployed. So there should no longer be any need to build these components locally, as was the case when #20 was reported.  

Of course if you are running the package from a git checkout, then the above doesn't apply, and your system will need to have a properly configured c/c++ build environment available.

What version of file-collection are you trying to use?   Windows native builds have been bundled since v1.0.5

If you are using a local checkout of the package, you can check your local build environment by running:

```bash
mkdir bsonTest
cd bsonTest
npm install bson
```

**Comment by Digital-Thor** [comment] 2015-06-06 23:38
Thanks.  I'm using file-collection 1.1.1.  Also, I am using git locally on my project, but not on the bson package. The error that I list above also occurs in the meteor-file-sample-app (which I cloned from Github), but the app appears to work.  Since I'm not really familiar with how to set up a c/c++ build environment, am I able to get away with using the "pure JS version" mentioned after the error, or will that limit performance of my app?  PS. I installed bson, but not sure what to do after that.

**Comment by vsivsi** [comment] 2015-06-07 00:07
The pure JS version will work, but performance will definitely be reduced.

Did the BSON npm package build correctly when you installed it on its own?

Output should look something like:
```
> bson-ext@0.1.7 install /Users/vsi/bsontest/node_modules/bson/node_modules/bson-ext
> (node-pre-gyp install --fallback-to-build) || (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/bson.node
  SOLINK_MODULE(target) Release/bson.node: Finished
bson@0.3.2 node_modules/bson
└── bson-ext@0.1.7 (nan@1.8.4, node-pre-gyp@0.6.4)
```

If that doesn't work, then your Windows environment doesn't have the tools required to build npm packages with native components like bson-ext (the native subpart of the bson package).

In any case, you shouldn't be confronting any of this because the binary components are pre-built on a properly configured -- Meteor owned -- Windows build machine when I deploy each version of the file-collection package to Atmosphere.

I've just looked at the detailed manifest for this package available by running:
```
meteor show vsivsi:file-collection --ejson
```

Something seems not quite right in that output.  The first version of file-collection that supported Windows was v1.0.5, and in the manifest it shows (note `"os.windows.x86_32"` under `architecturesOS`):
```json
    {
      "exports": [
        {
          "name": "FileCollection",
          "architectures": [
            "server",
            "web.browser",
            "web.cordova"
          ]
        }
      ],
      "implies": [],
      "name": "vsivsi:file-collection",
      "version": "1.0.5",
      "description": "file-collection is a Meteor.js package that cleanly extends Meteor's Collection metaphor for efficiently dealing with collections of files and their data. File Collections are fully reactive, so if you know how to use Meteor Collections, you already know most of what you need to begin working with this package. It also fully supports HTTP upload and download including support for authentication.",
      "summary": "Collections that efficiently store files using MongoDB GridFS, with built-in HTTP support",
      "git": "https://github.com/vsivsi/meteor-file-collection.git",
      "publishedBy": "vsivsi",
      "publishedOn": {
        "$date": 1427420769608
      },
      "installed": true,
      "architecturesOS": [
        "os.osx.x86_64",
        "os.linux.x86_64",
        "os.linux.x86_32",
        "os.windows.x86_32"
      ]
    }
```

However, more recent versions don't show that, only showing `"os"` in that slot, e.g. for v1.1.1:

```json
      "architecturesOS": [
        "os.osx.x86_64",
        "os.linux.x86_64",
        "os.linux.x86_32",
        "os"
      ]
```

I know for a fact that I've been doing the Windows builds without any issues on each version release, so I don't know if this is just a glitch in the output of this command, or if it reflects that my windows builds aren't actually "taking" for some reason. Unfortunately I don't have convenient access to a Windows 7 box to reproduce this, so I'll need to search around and see if this has been documented / reported by anyone else.  You are the first to raise a Windows specific issue about this on this package since before v1.0.5, but I really don't know how many Windows users there are of Meteor at this point.

Can you please try editing the `.meteor/versions` file of the sample app to use `vsivsi:file-collection@1.0.5` and see if that makes the "pure JS" warning go away?  If so that will be evidence that something is silently going wrong with the Atmosphere deployment builds that I'm doing each time I publish a new version...

Sorry for the long winded answer, but this kind of stuff is really frustrating to figure out when I can't reproduce it directly myself.

**Comment by vsivsi** [comment] 2015-06-07 00:19
I take that back, there was a previous report of a similar issue on Windows a while back, but it turned out to be a cross-platform code migration problem (you can't just copy all of the files from Linux to Windows and expect everything to work when there are native components!)

https://github.com/vsivsi/meteor-file-collection/issues/44

**Comment by vsivsi** [comment] 2015-06-07 00:30
I just logged into the Meteor Windows build machine again to try to rebuild v1.1.1, and the build worked without errors, and then I get the following error:
```
=> Errors while publishing build:                        
While publishing package build for vsivsi:file-collection:              
error: Cannot override existing build  
```
This leads me to believe that Atmosphere at least thinks there was a previous successful build of the package. But I guess that doesn't mean that on the user end of things it will recognize that pre-built native components are available and install them...  I'll keep hunting.

**Comment by vsivsi** [comment] 2015-06-07 01:17
I've just verified on one of Meteor's windows build machines that downgrading to file-collection v1.0.5 works without the "pure JS" warning.  I've also been able to reproduce the warning when using the current version of file-collection.  I'm unclear why this process worked one for v1.0.5, but seems to perhaps be failing in each subsequent version.  This may end up being a new Meteor issue if I can't figure out why this is happening.

**Comment by Digital-Thor** [comment] 2015-06-07 01:43
Thanks again. Knocking it back to v1.0.5 didn't get rid of the error (which by the way shows up four times in a row) when the sample app starts.  My project folder was also a migration from Ubuntu, but for the sample app, I did a fresh cloning to a new folder and also did a `meteor reset`.  Below is the response to `meteor show` if that's helpful.

```
>meteor show vsivsi:file-collection --ejson
{
  "versions": [
    {
      "exports": [
        {
          "name": "FileCollection",
          "architectures": [
            "server",
            "web.browser",
            "web.cordova"
          ]
        }
      ],
      "implies": [],
      "name": "vsivsi:file-collection",
      "version": "1.0.4",
      "description": "file-collection is a Meteor.js package that cleanly extends Meteor's Collection metaphor for efficiently dealing with collections of files and their data. File Collections are fully reactive, so if you know how to use Meteor Collections, you already know most of what you
need to begin working with this package. It also fully supports HTTP upload and download including support for authentication.",
      "summary": "Collections that efficiently store files using MongoDB GridFS, with built-in HTTP support",
      "git": "https://github.com/vsivsi/meteor-file-collection.git",
      "publishedBy": "vsivsi",
      "publishedOn": {
        "$date": 1427420095143
      },
      "installed": false,
      "architecturesOS": [
        "os.osx.x86_64",
        "os.linux.x86_64",
        "os.linux.x86_32"
      ]
    },
    {
      "exports": [
        {
          "name": "FileCollection",
          "architectures": [
            "server",
            "web.browser",
            "web.cordova"
          ]
        }
      ],
      "implies": [],
      "name": "vsivsi:file-collection",
      "version": "1.0.5",
      "description": "file-collection is a Meteor.js package that cleanly extends Meteor's Collection metaphor for efficiently dealing with collections of files and their data. File Collections are fully reactive, so if you know how to use Meteor Collections, you already know most of what you
need to begin working with this package. It also fully supports HTTP upload and download including support for authentication.",
      "summary": "Collections that efficiently store files using MongoDB GridFS, with built-in HTTP support",
      "git": "https://github.com/vsivsi/meteor-file-collection.git",
      "publishedBy": "vsivsi",
      "publishedOn": {
        "$date": 1427420769608
      },
      "installed": false,
      "architecturesOS": [
        "os.osx.x86_64",
        "os.linux.x86_64",
        "os.linux.x86_32",
        "os.windows.x86_32"
      ]
    },
    {
      "exports": [
        {
          "name": "FileCollection",
          "architectures": [
            "server",
            "web.browser",
            "web.cordova"
          ]
        }
      ],
      "implies": [],
      "name": "vsivsi:file-collection",
      "version": "1.0.6",
      "description": "file-collection is a Meteor.js package that cleanly extends Meteor's Collection metaphor for efficiently dealing with collections of files and their data. File Collections are fully reactive, so if you know how to use Meteor Collections, you already know most of what you
need to begin working with this package. It also fully supports HTTP upload and download including support for authentication.",
      "summary": "Collections that efficiently store files using MongoDB GridFS, with built-in HTTP support",
      "git": "https://github.com/vsivsi/meteor-file-collection.git",
      "publishedBy": "vsivsi",
      "publishedOn": {
        "$date": 1430353208264
      },
      "installed": false,
      "architecturesOS": [
        "os.linux.x86_64",
        "os.linux.x86_32",
        "os",
        "os.osx.x86_64"
      ]
    },
    {
      "exports": [
        {
          "name": "FileCollection",
          "architectures": [
            "server",
            "web.browser",
            "web.cordova"
          ]
        }
      ],
      "implies": [],
      "name": "vsivsi:file-collection",
      "version": "1.1.0",
      "description": "file-collection is a Meteor.js package that cleanly extends Meteor's Collection metaphor for efficiently dealing with collections of files and their data. File Collections are fully reactive, so if you know how to use Meteor Collections, you already know most of what you
need to begin working with this package. It also fully supports HTTP upload and download including support for authentication.",
      "summary": "Collections that efficiently store files using MongoDB GridFS, with built-in HTTP support",
      "git": "https://github.com/vsivsi/meteor-file-collection.git",
      "publishedBy": "vsivsi",
      "publishedOn": {
        "$date": 1431419290863
      },
      "installed": true,
      "architecturesOS": [
        "os.osx.x86_64",
        "os.linux.x86_64",
        "os.linux.x86_32",
        "os"
      ]
    },
    {
      "exports": [
        {
          "name": "FileCollection",
          "architectures": [
            "server",
            "web.browser",
            "web.cordova"
          ]
        }
      ],
      "implies": [],
      "name": "vsivsi:file-collection",
      "version": "1.1.1",
      "description": "file-collection is a Meteor.js package that cleanly extends Meteor's Collection metaphor for efficiently dealing with collections of files and their data. File Collections are fully reactive, so if you know how to use Meteor Collections, you already know most of what you
need to begin working with this package. It also fully supports HTTP upload and download including support for authentication.",
      "summary": "Collections that efficiently store files using MongoDB GridFS, with built-in HTTP support",
      "git": "https://github.com/vsivsi/meteor-file-collection.git",
      "publishedBy": "vsivsi",
      "publishedOn": {
        "$date": 1433122385859
      },
      "installed": true,
      "architecturesOS": [
        "os.osx.x86_64",
        "os.linux.x86_64",
        "os.linux.x86_32",
        "os"
      ]
    }
  ],
  "name": "vsivsi:file-collection",
  "maintainers": [
    "vsivsi"
  ],
  "totalVersions": 15
}
```

**Comment by vsivsi** [comment] 2015-06-07 02:15
Hmmm, this is all very confusing.  What exactly did you migrate from Ubuntu?  Did you copy a whole app project directory (including the full directory tree under `.meteor\`)?  If so, that definitely will not work.

Okay, here's something to try.  In the `meteor-file-sample-app` directory try:

```bash
git checkout d739c14a0d35703a724c97fbc737f1e88ea3928b
# You'll get a "detached HEAD" warning here, that's fine
meteor
```
This will run the sample app at the commit where v1.0.5 was added, and it should run with Meteor v1.0.5 also, which was the version of Meteor that that release of file-collection was built with (the only one that correctly shows `"os.windows.x86_32"` in the `architecturesOS` list.

Do you get the BSON warning in this case?

**Comment by Digital-Thor** [comment] 2015-06-07 03:30
I used to work on an Ubuntu VM hosted by Windows.  They shared a Meteor folder using Dropbox.  Now that Meteor for Windows is available,  I don't use Ubuntu anymore.  My other projects survived that fine, though occasionally, I had to do a `meteor reset`. The sample app was a completely clean install in an empty folder on Windows.

Here's the response to the `git checkout`:

```
git checkout d739c14a0d35703a724c97fbc737f1e88ea3928b
Note: checking out 'd739c14a0d35703a724c97fbc737f1e88ea3928b'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at d739c14... Bump file-collection version

E:\Data\Projects\MeteorLocal\vsi2>meteor
[[[[[ ~\E\Data\Projects\MeteorLocal\vsi2 ]]]]]

=> Started proxy.
=> Started MongoDB.

=> Meteor 1.1.0.2: official Windows support, new package version constraint solver.


This release is being downloaded in the background. Update your app to
Meteor 1.1.0.2 by running 'meteor update'.

=> Errors prevented startup:

   While checking for npm-bcrypt@0.7.8_1:
   error: No compatible build found

=> Your application has errors. Waiting for file change.
```

**Comment by vsivsi** [comment] 2015-06-07 03:35
Sorry, my mistake, please try commit `05c92cf5ff970173f65abf4df0e9cd610cf3fbff` instead.

**Comment by vsivsi** [comment] 2015-06-07 03:37
Also, I just opened a new issue on Meteor about the `"os.windows.x86_32"` vs `"os"` in the `architecturesOS` list anomaly.  We'll see what they say, should take a couple of days.

**Comment by Digital-Thor** [comment] 2015-06-07 04:45
You can take your victory bow Vaughn!  Meteor now starts up without any errors.  So over to MDG for them to investigate `publish-for-arch`.  Hopefully that will help a lot of other Windows users as well.  Thanks for your time in diagnosing it.

**Comment by vsivsi** [comment] 2015-06-07 19:12
Okay, that restores some sanity for me.  Yes, we'll see what MDG says about this.  If don't/can't help then I really don't know what to try next, because if their own package build/release process for Windows isn't working right...

**Comment by vsivsi** [comment] 2015-06-19 19:59
@Digital-Thor @lobosan  

Please try file-collection@1.1.4 on Windows.  It will hopefully resolve this issue.  Coincidentally, the mongodb node driver author has been busy removing the BSON native component over the past few days and just updated the driver with those changes, so hopefully that fixes this issue.  

I still need to do native builds of this package because there is also the native code kerberos subproject in mongodb, but that package is optional, so it shouldn't cause any warnings when missing.

Please let me know how it goes with file-collection@1.1.4

**Comment by lobosan** [comment] 2015-06-19 23:23
Yes, no warnings or errors now. Thanks

**Comment by vsivsi** [comment] 2015-06-20 16:22
@lobosan  Glad that fixed it for you, thanks for reporting back!  I'll wait to also hear from @Digital-Thor before closing this issue.

**Comment by Digital-Thor** [comment] 2015-10-13 19:06
Sorry I missed above post.  Yes, error in the OP is gone.  Thanks Vaughn.

**Comment by vsivsi** [comment] 2015-10-13 19:18
Great!

**Closed by vsivsi** 2015-10-13 19:18 UTC
Labels: help wanted
