### ISSUE TITLE
Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND'

### ISSUE THREAD

**Issue by lobosan** [vsivsi/meteor-file-collection#58] opened 2015-06-17 16:47 UTC
At first I want to thank you for your package. 
I'm having these errors every time I run my meteor app on Windows 8.1

```
I20150617-11:36:36.972(-5)? { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
W20150617-11:36:36.974(-5)? (STDERR) js-bson: Failed to load c++ bson extension, using pure JS version
I20150617-11:36:37.273(-5)? { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
W20150617-11:36:37.273(-5)? (STDERR) js-bson: Failed to load c++ bson extension, using pure JS version
I20150617-11:36:37.276(-5)? { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
I20150617-11:36:37.276(-5)? { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
W20150617-11:36:37.276(-5)? (STDERR) js-bson: Failed to load c++ bson extension, using pure JS version
W20150617-11:36:37.276(-5)? (STDERR) js-bson: Failed to load c++ bson extension, using pure JS version
```

**Comment by vsivsi** [comment] 2015-06-17 18:13
Duplicate of https://github.com/vsivsi/meteor-file-collection/issues/57
See also: https://github.com/meteor/meteor/issues/4521

**Closed by vsivsi** 2015-06-17 18:13 UTC
Labels: duplicate
