### ISSUE TITLE
Improve error messages when allow/deny accidentally called on client

### ISSUE THREAD

**Issue by rico** [vsivsi/meteor-file-collection#54] opened 2015-05-21 08:27 UTC
Thanks for the package, which I'm using in the context of exporting data to Excel (http://meteorpad.com/pad/2hjNqmwHjDvkxvLC5/Leaderboard).

However, I'm getting an error `Uncaught Error: allow: Invalid key: read`. It looks like Meteor does not know about that key in the allow object:

`var VALID_KEYS = ['insert', 'update', 'remove', 'fetch', 'transform'];`

I'm using Meteor 1.1.0.2 and vsivsi:file-collection 1.1.0

**Comment by vsivsi** [comment] 2015-05-21 09:04
Hi, I'm not seeing that error when I run the linked app on Meteorpad.  

In any case, file-collection implements and handles its own `allow`/`deny` logic, so the standard Meteor mongo collection "VALID_KEYS" don't apply:
https://github.com/vsivsi/meteor-file-collection/blob/master/gridFS_server.coffee#L126
https://github.com/vsivsi/meteor-file-collection/blob/master/gridFS_server.coffee#L54

So the only way that I can think of that you would be seeing the error you describe is either you have a bug and are accidentally calling allow/deny on a Mongo colleciton with the file-collection rules, or somehow the allow/deny functionality of your file-collection is being overwritten with the standard Mongo collection methods.  People have reported problems using other packages that change or replace the default Mongo object while using file-collection. In particular, the load ordering of packages is significant, but file-collection is proactive in generating warnings when it detects that the Mongo collection has changed after it loads: 
https://github.com/vsivsi/meteor-file-collection/blob/master/gridFS_server.coffee#L23

Anyway, I don't see the error you describe on Meteorpad and this is the first I've heard of this error occurring with the package.  If you can share a repo on github for a minimal app that reproduces the error in normal Meteor development mode, I'll be happy to take a look at it.

**Comment by rico** [comment] 2015-05-21 10:23
Hi, thank you for the quick and detailed answer. It may very well be that I'm doing something wrong - I'm really a novice.

I put together a quick test and get the same error: https://github.com/rico/meteor-file-collection

thanks.

**Comment by vsivsi** [comment] 2015-05-23 08:12
Hi, I just tried out your test app linked above and got no errors...

```
% git clone https://github.com/rico/meteor-file-collection.git mfcTest
Cloning into 'mfcTest'...
remote: Counting objects: 16, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 16 (delta 0), reused 16 (delta 0), pack-reused 0
Unpacking objects: 100% (16/16), done.
Checking connectivity... done.

% cd mfcTest
% meteor
[[[[[ ~/mfcTest ]]]]]                         

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
```

What environment are you running this in, and what versions of all related programs (Meteor etc.) are you using?

**Comment by vsivsi** [comment] 2015-05-23 22:14
Hi, I just got a pointer on another project. About version weirdness in meteor when specific versions aren't hard coded in some cases.  MeteorPad is specifically called out as maybe being affected by this issue. https://github.com/meteor/meteor/issues/4170

It really seems that you are somehow pulling in the old pre-1.0.0 version of this package (before the 'write' allow rules were added). Anyway, please make sure that the latest version of file-collection is being used, and this issue should go away.

**Comment by rico** [comment] 2015-05-24 08:52
Hi, thank you for taking the time to look at. I'm having the same environment as you - OS X 10.10.3 and Meteor 1.1.0.2. 

I removed and readded the package using:  `meteor add vsivsi:file-collection@1.1.0` but still get the same error in the console:

![invalid-key-read](https://cloud.githubusercontent.com/assets/92818/7787249/c7a15cb8-0202-11e5-965c-f398e8228f7b.png)

Interestingly, the error does not prevent proper functionality in dev mode, but crashes the application on production mode.

**Comment by vsivsi** [comment] 2015-05-24 10:53
Hi, what exactly is your "production mode"?   Can you try deploying the file-collection sample application in your production environment and see what happens?  https://github.com/vsivsi/meteor-file-sample-app

This really seems like an issue where when you deploy your application, somehow you are ending up with `file-collection@0.1.18` which is the last version before the `'read'` and `'write'` rules were added. This is the version that the Meteor issue I referenced above would cause to be loaded by default...  So however you are deploying to production, I'm about 90% sure you are not getting the correct version of the package.

If it's the 10% case (I'm wrong in my hunch), then something else is going very wrong with your file-collection objects, because they seem to be being converted back to normal Mongo collections...

**Comment by rico** [comment] 2015-05-24 13:25
Hi, with production mode I mean either running the app with `meteor --production` or deploying it using [arunoda/meteor-up](https://github.com/arunoda/meteor-up) `mup deploy`.

However, it seems I wasn't clear in my last message. I get the error in the console using any mode - but in development mode (`meteor`) it does not crash my app, whereas in the production modes it does.

If I start the app using `meteor -v --production`, I can confirm, that `vsivsi/meteor-file-collection` has version 1.1.0.

So I rather tend to the 10%. But how could this happen?

I also ran the file-sample app (https://github.com/vsivsi/meteor-file-sample-app) and did not get any error :-) strange.

**Comment by rico** [comment] 2015-05-24 14:09
I just figured it out. Moving the `FileCollection` definition from the `lib` to the `server` folder solved the problem for good :-)

I'm sorry holding you up with that - but I warned you I'm a novice ;-)

Thank you very much for your patience & help. The sample app put me on the right track.

**Comment by vsivsi** [comment] 2015-05-24 17:46
Just so I'm clear, the issue was that you were trying to call allow/deny on the client?   I should really have a case to catch that error with a more informative message.  Please confirm that's what was happening and if so I'll reopen this and fix that.  Thanks, -V

**Comment by vsivsi** [comment] 2015-05-24 18:54
Just one more tip: it would have been very helpful in the OP if you had clearly said that the error you were seeing was in the **client** console. This whole time I've been assuming that it was a server error because "who would run allow/deny on the client?" :smile:

**Comment by vsivsi** [comment] 2015-05-24 19:38
This has been fixed in `master`.  Will be released shortly in v1.1.1

**Comment by rico** [comment] 2015-05-25 11:40
Exactly, I tried to call allow / deny in the client, because my code was in the `lib` folder and I forgot to wrap allow / deny in `if( Meteor.isServer ) {...}`.

I'm sorry,I just wasn't aware of it - if I were, I didn't have had the problem :-) 

Obviously you are right, it doesn't make any sense to call allow / deny on the client. However, the `Mongo.Collection()` doesn't care. I have the allow / deny rules for my other collections in client code as well (in the `lib` folder, not wrapped in the `if( Meteor.isServer ) {...}`) and do not get any errors cause of that. So maybe this is why it took me so long to figure it out. Thank's again.

**Comment by vsivsi** [comment] 2015-06-03 03:30
allow/deny on the client now throw, as of v1.1.1 on Atmosphere now.

**Closed by vsivsi** 2015-06-03 03:30 UTC
Labels: enhancement
